name: Publicar en GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Construir aplicación Web Flet
        run: flet publish main.py --base-url /shunting-yard-flet

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Subir archivos web
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'

      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
